---
  - name: Uninstall MySQL
    hosts: all
    become: yes
    vars:
      - ansible_python_interpreter: /usr/bin/python3
    tasks:
      - name: Uninstall a MySQL server & client
        apt:
          name: "{{ item }}"
          state: absent
          purge: yes
        with_items:
          - mysql-common
          - mysql-community-client-plugins
          - mysql-community-client-core
          - mysql-community-client
          - mysql-client

          - mysql-community-server-core
          - mysql-community-server
          - mysql-server
      - name: Remove useless packages from the cache
        apt:
          autoclean: yes
      - name: Remove dependencies that are no longer required
        apt:
          autoremove: yes
		  
- name: Install MariaDB
    hosts: all
    become: yes
    vars:
      - ansible_python_interpreter: /usr/bin/python3
    tasks:
      - name: Install apt
        apt:
          name:
            - software-properties-common
            - dirmngr
            - apt-transport-https
      - name: Add an Apt signing key, uses whichever key is at the URL
        ansible.builtin.apt_key:
          url: https://mariadb.org/mariadb_release_signing_key.asc
          state: present
      - name: Add specified repository into sources list
        ansible.builtin.apt_repository:
          repo: deb [arch=amd64,arm64,ppc64el] https://mirror.docker.ru/mariadb/repo/10.6/ubuntu bionic main
          state: present
      - name: Update apt packages
        apt:
          update_cache: yes
          cache_valid_time: 3600
      - name: Install MariaDB server
        apt:
          name:
            - mariadb-server