Vagrant.configure("2") do |config|

config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime", run: "always"

config.vm.define "haproxy" do |vm|
vm.vm.box = "ubuntu/bionic64"
vm.vm.hostname = "haproxy"
vm.vm.network :private_network, ip: "192.168.33.2"

end

config.vm.define "logstash" do |vm|
vm.vm.box = "ubuntu/bionic64"
vm.vm.hostname = "logstash"
vm.vm.network :private_network, ip: "192.168.33.3"

end

config.vm.define "webui" do |vm|
vm.vm.box = "ubuntu/bionic64"
vm.vm.hostname = "webui"
vm.vm.network :private_network, ip: "192.168.33.4"

end

end
